[package]
name = "iseven_api"
version = "0.4.0"
edition = "2021"
license = "MIT"
description = "A Rust wrapper for isEven API"
homepage = "https://github.com/megascrapper/iseven-api-rust"
repository = "https://github.com/megascrapper/iseven-api-rust"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.4", features = ["json", "blocking"] }
serde = { version = "1.0.126", features = ["derive"] }
tokio = { version = "1.9.0", features = ["macros", "rt-multi-thread"] }
error-chain = "0.12.4"
thiserror = "1.0.30"
ansi_term = "0.12.1"
human-panic = "1.0.3"